---
title: "Moody #rstats"
subtitle: "Collecting and analyzing digital trace data with #rstats"
author: Michael W. Kearney
date: '`r Sys.Date()`'
output: github_document
---

### Description

This is the dedicated repository for the Fall 2018 workshop on collecting and
analyzing digital trace data using R/Rstudio hosted by the Moody College of
Communication at the University of Texas-Austin. 

The hourly breakdown of the workshop, which consists of two 3-hour sessions, 
is provided below. Note that each section has a corresponding *follow-along*
Rmarkdown document, which can be found in the main folder in this
repository.

### [1: Intro to R/Rstudio](01-setup.Rmd)
+ Intro to R/Rstudio
+ Setting up packages
+ R basics
+ Data sets

### [2: Data vizualization](02-visualize.Rmd)
+ Intro to **{tidyverse}**
+ Data visualization
+ Data frames
+ R projects `.Rproj`

### [3: Data wrangling](03-wrangle.Rmd)
+ **{magrittr}**'s `%>%` (pipe)
+ **{dplyr}**
+ **{tidyr}**

### [4: Web data](04-web-data.Rmd)

+ Web scraping
+ APIs
+ Examples

### [5: Twitter API (rtweet)](05-twitter-api.Rmd)
+ Statuses
+ Friends/followers
+ Other

### [6: Machine learning](06-machine-learning.Rmd)
+ Gradient models **{gbm}**
+ Neural networks

